name: Build Util

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: set NOW
      run: echo "::set-env name=NOW::v$(date +'%Y%m%d.%H%M%S')"
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "casperhost-name"
        tag: ${{ env.NOW }}
        token: ${{ secrets.GITHUB_TOKEN }}