name: Build Util

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "casperhost-name"
        token: ${{ secrets.GITHUB_TOKEN }}
